database:
  file: "data/bentoData.db"

data_files:
  density: "data/density.csv"
  items: "data/items.csv"
  nutrition: "data/nutrition.csv"
  price: "data/price.csv"

nutrition:
  fat: 20
  protein: 50
  carb: 100
  salt: 5

optimizer:
  max_volume: 100
  min_mass_per_category: 0.5
  constraints:
    fat: ">="
    protein: ">="
    carb: "<="
    salt: "<="