database:
  file: "data/bentoData.db"

data_path: "data/"

data_files:
  density: "density.csv"
  items: "items.csv"
  nutrition: "nutrition.csv"
  price: "price.csv"

nutrition:
  fat: 20
  protein: 50
  carb: 100
  salt: 5

optimizer:
  max_volume: 100
  min_mass_per_category: 0.5
  constraints:
    fat: ">="
    protein: ">="
    carb: "<="
    salt: "<="