database:
  file: "data/bentoData.db"

data_path: "data/"

data_files:
  categories: "categories.csv"
  items: "items.csv"
  prices: "prices.csv"

nutrition:
  fat: 20
  protein: 50
  carb: 100
  salt: 5

optimizer:
  max_volume: 100
  min_mass_per_category: 0.5
  constraints:
    fat: ">="
    protein: ">="
    carb: "<="
    salt: "<="

export:
  filename: "bentoKaze"
  formats: ["lp", "mps"]
  output_dir: "models"